# Generated by Django 4.1 on 2022-08-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
