# Generated by Django 4.1 on 2022-08-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
        ('post', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.userprofile'),
        ),
    ]
